# Generated by Django 4.2 on 2023-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(default="")),
                ("title", models.CharField(max_length=250)),
                ("image_url", models.URLField(verbose_name="")),
                ("source_url", models.URLField(verbose_name="")),
            ],
        ),
    ]
