# Generated by Django 4.2 on 2023-05-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogmodel",
            name="image_url",
        ),
    ]
